@startuml Different flow
skinparam sequenceMessageAlign right

actor "PYME" as A 
database "PartnerManagement Database" as BDPartnerManagement
database "ejemplo" as Ejemplo 

activate BDPartnerManagement
A ->> BDPartnerManagement: pyme registra en bd
BDPartnerManagement->>A: Respuesta
deactivate BDPartnerManagement




@enduml